package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConferenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConferenceAllPropertiesEquals(Conference expected, Conference actual) {
        assertConferenceAutoGeneratedPropertiesEquals(expected, actual);
        assertConferenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConferenceAllUpdatablePropertiesEquals(Conference expected, Conference actual) {
        assertConferenceUpdatableFieldsEquals(expected, actual);
        assertConferenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConferenceAutoGeneratedPropertiesEquals(Conference expected, Conference actual) {
        assertThat(expected)
            .as("Verify Conference auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConferenceUpdatableFieldsEquals(Conference expected, Conference actual) {
        assertThat(expected)
            .as("Verify Conference relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getDate()).as("check date").isEqualTo(actual.getDate()))
            .satisfies(e -> assertThat(e.getPalce()).as("check palce").isEqualTo(actual.getPalce()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConferenceUpdatableRelationshipsEquals(Conference expected, Conference actual) {
        assertThat(expected)
            .as("Verify Conference relationships")
            .satisfies(e -> assertThat(e.getSpeakers()).as("check speakers").isEqualTo(actual.getSpeakers()));
    }
}
